name: CI-feature-branch
concurrency: ci-${{ github.ref }}
on:
  push:
    branches: ["*", "!main", "!master", "!skip/*"]
  workflow_dispatch:
jobs:
  test-provider-cfn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        working-directory: GitHubOIDCProvider
        run: |
          npm install
      - name: Build
        working-directory: GitHubOIDCProvider
        run: |
          npm run build
      - name: Test
        working-directory: GitHubOIDCProvider
        run: |
          npm test
  test-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          npm install
      - name: Test
        run: |
          npm test
