name: CI
concurrency: ci-${{ github.ref }}
on:
  push:
    branches: [master, main]
  workflow_dispatch:
jobs:
  test-provider-cfn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        working-directory: GitHubOIDCProvider
        run: |
          npx pnpm install
      - name: Build
        working-directory: GitHubOIDCProvider
        run: |
          npx pnpm run build
      - name: Test
        working-directory: GitHubOIDCProvider
        run: |
          npx pnpm test
      - name: itest
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.PROVIDER_DEPLOYER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROVIDER_DEPLOYER_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.REGION }}
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
        working-directory: GitHubOIDCProvider
        run: |
          npx pnpm cdk-deploy
          aws iam get-open-id-connect-provider --open-id-connect-provider-arn arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/token.actions.githubusercontent.com
          # now use it
          # deploy a role using the provider
      - name: deploy role stack
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.PROVIDER_DEPLOYER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.  PROVIDER_DEPLOYER_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.REGION }}
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
        working-directory: ExampleApp
        run: |
          npx pnpm deploy-role
      # - name: configure AWS creds
  test-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          npm install
      - name: Test
        run: |
          npm test
