name: CI
concurrency: ci-${{ github.ref }}
on:
  push:
    branches: [master, main]
  workflow_dispatch:
jobs:
  test-provider-cfn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        working-directory: GitHubOIDCProvider
        run: |
          npx pnpm install
      - name: Build
        working-directory: GitHubOIDCProvider
        run: |
          npx pnpm run build
      - name: Test
        working-directory: GitHubOIDCProvider
        run: |
          npx pnpm test
  test-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          npm install
      - name: Test
        run: |
          npm test
